#!/bin/zsh
# This hook is run after a new virtualenv is created and before it is activated.
# argument: name of new environment
# Automatically set django settings for the virtualenv
echo "export DJANGO_SETTINGS_MODULE=$1.settings" >> "$1/bin/activate"
